//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomReservation
    {
        public int ReservationCode { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public double TotalPrice { get; set; }
        public int GuestID { get; set; }
        public int RoomID { get; set; }
    
        public virtual Guest Guest { get; set; }
        public virtual RoomDetail RoomDetail { get; set; }
    }
}
